package com.postgres.services.database.query_builder.dialects;


public class PostgreSQLDialect implements SQLDialect {

    /**
     * Sintaxis recomendada para auto-incremento en PostgreSQL moderno.
     * Se puede usar también "SERIAL" en versiones antiguas.
     * @return String con la cláusula de identidad
     */
    @Override
    public String getAutoIncrement() {
        return "GENERATED BY DEFAULT AS IDENTITY";
    }

    /**
     * Genera la cláusula LIMIT para PostgreSQL.
     */
    @Override
    public String getLimit(int count) {
        return "LIMIT " + count;
    }

    /**
     * IF NOT EXISTS es soportado por PostgreSQL para creación condicional.
     */
    @Override
    public String getIfNotExists() {
        return "IF NOT EXISTS";
    }

    /**
     * Mapea tipos básicos a su representación en PostgreSQL.
     */
    @Override
    public String getDataType(String baseType, Integer length, Integer precision, Integer scale) {
        switch (baseType.toUpperCase()) {
            case "VARCHAR":
                return length != null ? "VARCHAR(" + length + ")" : "VARCHAR(255)";
            case "DECIMAL":
            case "NUMERIC":
                return precision != null && scale != null ?
                    "NUMERIC(" + precision + "," + scale + ")" : "NUMERIC(10,2)";
            case "TEXT":
                return "TEXT";
            case "BOOLEAN":
                return "BOOLEAN";
            case "INT":
            case "INTEGER":
                return "INTEGER";
            default:
                return baseType;
        }
    }

    /**
     * Concatenación de cadenas usando el operador || de PostgreSQL.
     */
    @Override
    public String getStringConcatenation(String... parts) {
        return "(" + String.join(" || ", parts) + ")";
    }

    /**
     * Tipo fecha básico.
     */
    @Override
    public String getDateFormat() {
        return "DATE";
    }

    @Override
    public String getBooleanTrue() {
        return "TRUE";
    }

    @Override
    public String getBooleanFalse() {
        return "FALSE";
    }

    /**
     * Delimita identificadores con comillas dobles y duplica comillas internas.
     */
    @Override
    public String getQuoteIdentifier(String identifier) {
        if (identifier == null) return null;
        String escaped = identifier.replace("\"", "\"\"");
        return "\"" + escaped + "\"";
    }

    @Override
    public String getCountFunction() {
        return "COUNT";
    }

    @Override
    public String getSumFunction() {
        return "SUM";
    }

    @Override
    public String getAvgFunction() {
        return "AVG";
    }

    @Override
    public String getMinFunction() {
        return "MIN";
    }

    @Override
    public String getMaxFunction() {
        return "MAX";
    }

    @Override
    public String getUpperFunction() {
        return "UPPER";
    }

    @Override
    public String getLowerFunction() {
        return "LOWER";
    }

    /**
     * Preferir CHAR_LENGTH para longitud de texto en PostgreSQL.
     */
    @Override
    public String getLengthFunction() {
        return "CHAR_LENGTH";
    }

    @Override
    public String getSubstringFunction() {
        return "SUBSTRING";
    }

    /**
     * Timestamp actual preferido en PostgreSQL.
     */
    @Override
    public String getCurrentTimestamp() {
        return "CURRENT_TIMESTAMP";
    }

    @Override
    public String getNullFunction() {
        return "NULL";
    }

    @Override
    public String getCoalesceFunction() {
        return "COALESCE";
    }
}