import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class App {
    
    private static String user = "system";
    private static String password = "oracle123";
    private static String url = "jdbc:oracle:thin:@localhost:1521:xe";
    
    private static void testConnection(){
        try(Connection conn = DriverManager.getConnection(url, user, password)) {
            if (conn != null) {
                System.out.println("Connected to the database!");
            } else {
                System.out.println("Failed to make connection!");
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    private static Connection getConnection() throws SQLException {
        Connection connection; 
        try {
            connection = DriverManager.getConnection(url, user, password);
        } catch (SQLException SQLException) {
            throw new SQLException("Oracle JDBC Driver not found", SQLException);
        }
        return connection;
    }


    private static void createUser(){
        try(Connection conn = getConnection()) {
            // Create user
            String createUserQuery = "CREATE USER bibliotecaClemente IDENTIFIED BY biblioteca123";
            PreparedStatement pss = conn.prepareStatement(createUserQuery);
            pss.execute();
            
            // Grant privileges
            String grantQuery = "GRANT CONNECT, RESOURCE, DBA TO biblioteca";
            PreparedStatement grantStmt = conn.prepareStatement(grantQuery);
            grantStmt.execute();
            
            System.out.println("User 'biblioteca' created successfully.");
        } catch (SQLException e) {
            System.out.println("Error creating user: " + e.getMessage());
        }
    }

    private static void createSchema(){
        try(Connection conn = getConnection()) {
            // In Oracle, schema is created automatically when user is created
            // But we can create additional objects in the schema
            String alterUserQuery = "ALTER USER bibliotecaClemente DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS";
            PreparedStatement pss = conn.prepareStatement(alterUserQuery);
            pss.execute();
            System.out.println("Schema 'bibliotecaClemente  ' configured successfully.");
        } catch (SQLException e) {
            System.out.println("Error configuring schema: " + e.getMessage());
        }
    }

    private static void createTable(){
        try(Connection conn = getConnection()) {
            String createTableQuery = "CREATE TABLE biblioteca.libros (" +
                    "idLibro NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," + 
                    "isbn VARCHAR2(13) NOT NULL," +
                    "titulo VARCHAR2(255) NOT NULL," +
                    "autor VARCHAR2(255)," +
                    "anho NUMBER," +
                    "disponible NUMBER(1) DEFAULT 1," +
                    "portada BLOB)";
            PreparedStatement pss = conn.prepareStatement(createTableQuery); 
            pss.execute();
            System.out.println("Table 'libros' created successfully.");
        } catch (SQLException e) {
            System.out.println("Error creating table: " + e.getMessage());
        }
    }

    private static void makeDB(){
        System.out.println("Creating Oracle database structure...");
        createUser();
        createSchema();
        createTable();
        System.out.println("Database setup completed.");
    }

    public static void main(String[] args) throws Exception {
        testConnection();
        makeDB();
    }
}
